"""Credential (cookie) management + liveness validation.

Pinterest private boards are reached with the browser session cookies. The user
pastes either a Netscape `cookies.txt` (what browser extensions like
"Get cookies.txt" export) or a JSON cookie array (Cookie-Editor style); we
normalise both to a Netscape file on disk that gallery-dl consumes via
`--cookies`.

Validation is a heuristic liveness check — Pinterest exposes no stable public
"am I logged in" API — so we (1) confirm the session cookie is present and not
past its expiry, then (2) best-effort hit a login-gated page and see whether we
get bounced to /login.
"""

from __future__ import annotations

import http.cookiejar
import json
import re
import time
from dataclasses import dataclass
from pathlib import Path

import httpx

from app.config import get_settings

SESSION_COOKIE = "_pinterest_sess"
_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0 Safari/537.36"
)


def cookies_path(cred_id: int) -> Path:
    return get_settings().cookies_dir / f"{cred_id}.txt"


# --------------------------------------------------------------------------- #
# writing / normalising
# --------------------------------------------------------------------------- #
_NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# Generated by Pinchive\n"


def save_cookies_text(cred_id: int, raw: str) -> int:
    """Persist pasted cookies (Netscape or JSON) as a Netscape file.

    Returns the number of cookies written.
    """
    raw = raw.strip()
    if not raw:
        raise ValueError("empty cookie payload")

    if raw[0] in "[{":
        lines = _json_to_netscape_lines(raw)
    else:
        lines = _clean_netscape_lines(raw)

    if not lines:
        raise ValueError("no cookies parsed from input")

    path = cookies_path(cred_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_NETSCAPE_HEADER + "\n".join(lines) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass  # best effort on platforms without POSIX perms
    return len(lines)


def _clean_netscape_lines(raw: str) -> list[str]:
    out: list[str] = []
    for line in raw.splitlines():
        s = line.rstrip("\n")
        if not s.strip() or s.lstrip().startswith("#"):
            continue
        # Accept both real tabs and space-separated exports.
        parts = s.split("\t")
        if len(parts) != 7:
            parts = s.split()
        if len(parts) < 7:
            continue
        out.append("\t".join(parts[:7]))
    return out


def _json_to_netscape_lines(raw: str) -> list[str]:
    data = json.loads(raw)
    if isinstance(data, dict):
        data = data.get("cookies", [])
    out: list[str] = []
    for c in data:
        name = c.get("name")
        value = c.get("value", "")
        if not name:
            continue
        domain = c.get("domain") or ".pinterest.com"
        if not domain.startswith("."):
            domain = "." + domain.lstrip(".")
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = c.get("expirationDate") or c.get("expires") or 0
        try:
            expiry = int(float(expiry))
        except (TypeError, ValueError):
            expiry = 0
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        out.append(
            "\t".join([domain, include_sub, path, secure, str(expiry), name, str(value)])
        )
    return out


# --------------------------------------------------------------------------- #
# reading / validation
# --------------------------------------------------------------------------- #
@dataclass
class ValidationResult:
    active: bool
    message: str
    rotated: bool = False  # true when a keep-alive persisted refreshed cookies


# Pinterest embeds `"is_authenticated": true|false` in the settings page's
# initial-state JSON. That's the reliable liveness signal — the final URL is
# not: a logged-out /settings/ still returns 200 (SPA shell) and just redirects
# to the home page.
_AUTH_TRUE = re.compile(r'"is_authenticated"\s*:\s*true')
_AUTH_FALSE = re.compile(r'"is_authenticated"\s*:\s*false')


def _classify(r: httpx.Response) -> ValidationResult:
    if r.status_code in (401, 403):
        return ValidationResult(False, f"unauthenticated (status {r.status_code})")
    body = r.text
    if _AUTH_TRUE.search(body):
        return ValidationResult(True, "logged in")
    if _AUTH_FALSE.search(body):
        return ValidationResult(False, "not logged in — session invalid")
    final = str(r.url)
    if "/login" in final or final.rstrip("/") == "https://www.pinterest.com":
        return ValidationResult(False, "redirected away from settings — session invalid")
    if "/settings" in final and r.status_code == 200:
        return ValidationResult(True, "settings reachable")
    return ValidationResult(False, f"unknown auth state (status {r.status_code})")


def _load_jar(path: Path) -> http.cookiejar.MozillaCookieJar:
    jar = http.cookiejar.MozillaCookieJar(str(path))
    jar.load(ignore_discard=True, ignore_expires=True)
    return jar


def _session_cookie(jar: http.cookiejar.MozillaCookieJar):
    for c in jar:
        if c.name == SESSION_COOKIE:
            return c
    return None


def validate_cookies(path: Path, *, network: bool = True) -> ValidationResult:
    if not path.exists():
        return ValidationResult(False, "no cookie file")

    try:
        jar = _load_jar(path)
    except (OSError, http.cookiejar.LoadError) as e:
        return ValidationResult(False, f"unreadable cookie file: {e}")

    sess = _session_cookie(jar)
    if sess is None:
        return ValidationResult(False, f"missing {SESSION_COOKIE} cookie")
    if sess.expires and sess.expires < time.time():
        return ValidationResult(False, "session cookie expired (by date)")

    if not network:
        return ValidationResult(True, "session cookie present")

    return _network_check(jar)


def _network_check(jar: http.cookiejar.MozillaCookieJar) -> ValidationResult:
    cookies = httpx.Cookies()
    for c in jar:
        cookies.set(c.name, c.value or "", domain=c.domain, path=c.path)
    try:
        with httpx.Client(
            headers={"User-Agent": _UA},
            cookies=cookies,
            follow_redirects=True,
            timeout=15.0,
        ) as client:
            r = client.get("https://www.pinterest.com/settings/")
    except httpx.HTTPError as e:
        # Network hiccup shouldn't flip a credential to "expired".
        return ValidationResult(True, f"cookie present; live check failed: {e}")

    return _classify(r)


def refresh_session(path: Path) -> ValidationResult:
    """Keep-alive: make an authenticated request and persist any rotated cookies.

    Pinterest issues fresh `_pinterest_sess` values via Set-Cookie on activity
    (a sliding session). We drive that jar in-place through httpx, then — only
    when the session is confirmed live — write it back to the Netscape file so
    gallery-dl always has the newest cookie. Run periodically (see the worker
    cron) this keeps a registered session alive without re-pasting.

    We never persist on a login-redirect: that would clobber a good cookie with
    logged-out junk on a transient failure.
    """
    if not path.exists():
        return ValidationResult(False, "no cookie file")
    try:
        jar = _load_jar(path)
    except (OSError, http.cookiejar.LoadError) as e:
        return ValidationResult(False, f"unreadable cookie file: {e}")

    sess = _session_cookie(jar)
    if sess is None:
        return ValidationResult(False, f"missing {SESSION_COOKIE} cookie")
    if sess.expires and sess.expires < time.time():
        return ValidationResult(False, "session cookie expired (by date)")

    # Passing the jar to httpx.Cookies makes httpx update it in place from every
    # response's Set-Cookie.
    cookies = httpx.Cookies(jar)
    try:
        with httpx.Client(
            headers={"User-Agent": _UA},
            cookies=cookies,
            follow_redirects=True,
            timeout=15.0,
        ) as client:
            r = client.get("https://www.pinterest.com/settings/")
    except httpx.HTTPError as e:
        return ValidationResult(True, f"cookie present; keep-alive failed: {e}")

    verdict = _classify(r)
    if not verdict.active:
        # Don't persist logged-out cookies over a good file.
        return verdict

    try:
        jar.save(str(path), ignore_discard=True, ignore_expires=True)
        try:
            path.chmod(0o600)
        except OSError:
            pass
    except OSError as e:
        return ValidationResult(True, f"live, but could not persist rotation: {e}")

    return ValidationResult(True, "live — cookies rotated", rotated=True)
